import { Poppins } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"], // Tambahkan variasi berat sesuai kebutuhan
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Terapkan font Poppins di seluruh aplikasi */}
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
